include: package:all_lint_rules_community/all.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_bindings.dart"
    - "lib/generated/"
  errors:
    included_file_warning: ignore

linter:
  rules:
    # Incompatible with: avoid_types_on_closure_parameters, omit_local_variable_types.
    always_specify_types: false
    # Incompatible with: avoid_final_parameters.
    prefer_final_parameters: false
    # Incompatible with: prefer_final_locals.
    unnecessary_final: false
    # Incompatible with: prefer_double_quotes.
    prefer_single_quotes: false
    # Incompatible with: prefer_relative_imports.
    always_use_package_imports: false
    # Unnecessary for an application project.
    public_member_api_docs: false
