name: ecg_monitor
description: Yet another electrocardiogram monitor app.

publish_to: "none"

version: 1.1.0+3

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  go_router: ^6.0.1
  logger_flutter_plus: ^1.0.5
  path: ^1.8.2
  path_provider: ^2.0.12
  riverpod_annotation: ^1.0.6
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dependency_validator: ^3.2.2
  build_runner: ^2.3.2
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/model.pt
    - assets/debug/
