name: ecg_monitor
description: Yet another electrocardiogram monitor app.

publish_to: "none"

version: 0.2.0+2

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  riverpod_annotation: ^1.0.6
  salomon_bottom_bar: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dependency_validator: ^3.2.2
  build_runner: ^2.3.2
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
