name: ecg_monitor
description: Yet another electrocardiogram monitor app.

publish_to: "none"

version: 0.35.6+61

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  animations: ^2.0.7
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  duration_picker: ^1.1.1
  ffi: ^2.0.1
  file_picker: ^5.2.10
  fl_chart: ^0.62.0
  flex_color_picker: ^3.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_ume: ^1.1.2
  flutter_ume_kit_clean_local_data: ^1.0.0
  flutter_ume_kit_console: ^1.1.0
  flutter_ume_kit_designer_check: ^1.0.0
  flutter_ume_kit_device: ^1.0.0
  flutter_ume_kit_dio: ^2.0.0+3
  flutter_ume_kit_perf: ^1.0.1
  flutter_ume_kit_shared_preferences: ^1.0.0
  flutter_ume_kit_show_code: ^1.0.1
  flutter_ume_kit_slow_animation: ^1.0.0
  flutter_ume_kit_ui: ^1.1.1
  freezed_annotation: ^2.2.0
  functional_widget_annotation: ^0.10.0
  go_router: ^6.5.8
  intl: ^0.17.0
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  logging: ^1.1.1
  package_info_plus: ^3.1.0
  path: ^1.8.2
  path_provider: ^2.0.14
  pretty_dio_logger: ^1.3.1
  quiver: ^3.2.1
  restart_app: ^1.1.2
  riverpod_annotation: ^2.1.1
  sentry_dio: ^7.4.2
  sentry_flutter: ^7.4.2
  sentry_logging: ^7.4.2
  shared_preferences: ^2.1.0
  time_range_picker: ^2.2.0
  url_launcher: ^6.1.10

dev_dependencies:
  all_lint_rules_community: ^0.0.31
  build_runner: ^2.3.3
  dependency_validator: ^3.2.2
  ffigen: ^7.2.10
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  functional_widget: ^0.10.1
  isar_generator: ^3.1.0
  json_serializable: ^6.6.1
  path_provider_platform_interface: ^2.0.6
  riverpod_generator: ^2.2.1

dependency_overrides:
  flutter_ume_kit_clean_local_data:
    git:
      url: https://github.com/CCXXXI/flutter_ume_kits.git
      path: packages/flutter_ume_kit_clean_local_data
  flutter_ume_kit_console:
    git:
      url: https://github.com/CCXXXI/flutter_ume.git
      path: kits/flutter_ume_kit_console
  flutter_ume_kit_designer_check:
    git:
      url: https://github.com/CCXXXI/flutter_ume_kits.git
      path: packages/flutter_ume_kit_designer_check
  flutter_ume_kit_dio:
    git:
      url: https://github.com/CCXXXI/flutter_ume_kits.git
      path: packages/flutter_ume_kit_dio
  flutter_ume_kit_perf:
    git:
      url: https://github.com/CCXXXI/flutter_ume.git
      path: kits/flutter_ume_kit_perf
  flutter_ume_kit_shared_preferences:
    git:
      url: https://github.com/CCXXXI/flutter_ume_kits.git
      path: packages/flutter_ume_kit_shared_preferences
  flutter_ume_kit_show_code:
    git:
      url: https://github.com/CCXXXI/flutter_ume.git
      path: kits/flutter_ume_kit_show_code
  flutter_ume_kit_slow_animation:
    git:
      url: https://github.com/CCXXXI/flutter_ume_kits.git
      path: packages/flutter_ume_kit_slow_animation
  flutter_ume_kit_ui:
    git:
      url: https://github.com/CCXXXI/flutter_ume.git
      path: kits/flutter_ume_kit_ui

flutter:
  uses-material-design: true
  assets:
    - assets/model.pt
    - ios/Classes/PanTompkinsQRS/LICENSE

flutter_intl:
  enabled: true
