name: upload
description: 'Upload artifact & Release if needed'
inputs:
  files:
    description: 'Files to upload'
runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@v3
      with:
        path: ${{ inputs.files }}
    - if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ inputs.files }}
