name: setup-android
description: 'Setup Java and Flutter'
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: subosito/flutter-action@v2
