// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to PanTompkinsQRS
class PanTompkinsQRS {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PanTompkinsQRS(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PanTompkinsQRS.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void init(
    int fs,
  ) {
    return _init(
      fs,
    );
  }

  late final _initPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>('init');
  late final _init = _initPtr.asFunction<void Function(int)>();

  bool panTompkins(
    double sample,
  ) {
    return _panTompkins(
      sample,
    );
  }

  late final _panTompkinsPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Float)>>('panTompkins');
  late final _panTompkins = _panTompkinsPtr.asFunction<bool Function(double)>();
}
