name: build

on:
  push:
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-android

      - run: flutter build apk --split-per-abi

      - if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/apk/release/*.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-flutter

      - run: flutter build ios --no-codesign

      - if: startsWith(github.ref, 'refs/tags/v')
        uses: vimtor/action-zip@v1.1
        with:
          files: build/ios/iphoneos/Runner.app
          dest: Runner.app.zip
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: Runner.app.zip
