name: sentry

on:
  push:
    tags:
      - 'v*'

jobs:
  sentry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@master
        id: yq
        with:
          cmd: yq '.version' 'pubspec.yaml'
      - uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ccxxxi
          SENTRY_PROJECT: ecg_monitor
        with:
          environment: production
          version: io.github.ccxxxi.ecg_monitor@${{ steps.yq.outputs.result }}
